### ISSUE TITLE
关于代码块问题~

### ISSUE THREAD

**Issue by YvanZh** [abelsu7/hexo-theme-indigo-plus#1]
修改了_config.yml文件的prims代码主题，网站加载的时候也加载了对应js和css，但是代码块还是没有改变。求大佬捞一把~

**Comment by abelsu7** [comment]
@YvanZh 主题根目录下的`_config.yml`里要**禁用样式文件的 CDN**：

```yaml
# 设置为 true 发布后将使用 unpkg cdn 最新的主题样式
# 如果想让你的自定义样式生效，把此项设为 false
cdn: false
```

**Comment by abelsu7** [comment]
@YvanZh 好像不是这个问题。。。我再看下

**Comment by abelsu7** [comment]
@YvanZh Hexo 默认的渲染引擎`hexo-renderer-marked`在渲染代码块时没在`<code></code>`标签中添加`class=lang-*`属性，导致`prism.js`无法识别代码块。

在**博客根目录**下执行以下命令，使用`hexo-renderer-kramed`**替换原渲染引擎**就可以了：

```bash
npm uninstall hexo-renderer-marked --save
npm install hexo-renderer-kramed --save
```

可以参见[这里](https://abelsu7.top/2018/10/29/hexo-mathjax/#替换默认渲染引擎)。

**Comment by YvanZh** [comment]
> @YvanZh Hexo 默认的渲染引擎`hexo-renderer-marked`在渲染代码块时没在`<code></code>`标签中添加`class=lang-*`属性，导致`prism.js`无法识别代码块。
> 
> 在**博客根目录**下执行以下命令，使用`hexo-renderer-kramed`**替换原渲染引擎**就可以了：
> 
> ```shell
> npm uninstall hexo-renderer-marked --save
> npm install hexo-renderer-kramed --save
> ```
> 
> 可以参见[这里](https://abelsu7.top/2018/10/29/hexo-mathjax/#%E6%9B%BF%E6%8D%A2%E9%BB%98%E8%AE%A4%E6%B8%B2%E6%9F%93%E5%BC%95%E6%93%8E)。

你好，我本来就是使用的kramed，没有使用marked。感觉很奇怪，倒腾很久没找到原因😫

**Comment by abelsu7** [comment]
需要在博客根目录下的`_config.yml`中将`highlight`设置为`false`，之后`hexo clean`，重新生成静态页面后再启动服务器试试

**Comment by YvanZh** [comment]
哇，解决了，但是貌似出现了识别错误的问题😭
![image](https://user-images.githubusercontent.com/42346979/55684278-feab4f00-597b-11e9-9fae-eff7d4e73565.png)

**Comment by abelsu7** [comment]
@YvanZh 代码块必须**指定语言名称**，才会在渲染时给`code`标签添加`class="lang-xxx"`的属性，这样`prism.js`才能识别到代码块并对其进行高亮。

至于代码块中有白框的问题，是因为你的代码块是紧挨着列表元素写的，被识别成了行内代码。

![](http://qiniu.abelsu7.cn/indigo-plus-1.png)

今天我会更新一波，在`source/css/_partial/article.less`中去掉`border`这个属性（第`446`行），晚上记得`git pull`一下~

**Comment by YvanZh** [comment]
@abelsu7 嗯嗯，好滴，感谢大佬，期待更新~ 指定了语言之后渲染成功啦。然后代码我是这么写的：

```
1. 首先这么来：

    ```bash
    git pull
    ```

2. 然后这么来：
```

也就是列表和代码块用空行隔开了，按道理来说应该没问题了，但是还是识别成了行内代码，我再尝试一下。再次感谢大佬耐心解答~🖖

**Comment by YvanZh** [comment]
@abelsu7 去掉了`border`属性，白框没有了，但是还有半个字符的间隔。确实是被识别为了行内代码的锅。
![image](https://user-images.githubusercontent.com/42346979/55699563-e8de6e00-59fd-11e9-918c-8f8c276dac28.png)

**Comment by abelsu7** [comment]
已更新，参见`README.md`。

代码块尽量另起一段写，可以使用`1.XXX`这种不加空格的方式来代替`1. XXX`的自动标号。

**Comment by YvanZh** [comment]
@abelsu7 大佬赛高！

**Comment by shengbinyu** [comment]
修改kramed中/lib/kramed.js和 renderer.js 中的 langPrefix: 'lang-'为langPrefix: ''便可以正常使用prism。

**Comment by shengbinyu** [comment]
> @YvanZh Hexo 默认的渲染引擎`hexo-renderer-marked`在渲染代码块时没在`<code></code>`标签中添加`class=lang-*`属性，导致`prism.js`无法识别代码块。
> 
> 在**博客根目录**下执行以下命令，使用`hexo-renderer-kramed`**替换原渲染引擎**就可以了：
> 
> ```shell
> npm uninstall hexo-renderer-marked --save
> npm install hexo-renderer-kramed --save
> ```
> 
> 可以参见[这里](https://abelsu7.top/2018/10/29/hexo-mathjax/#%E6%9B%BF%E6%8D%A2%E9%BB%98%E8%AE%A4%E6%B8%B2%E6%9F%93%E5%BC%95%E6%93%8E)。

修改kramed中/lib/kramed.js和 /lib/renderer.js 中的 langPrefix: 'lang-'为langPrefix: ''便可以正常使用prism。
