### ISSUE TITLE
关于锚点失效的问题~

### ISSUE THREAD

**Issue by YvanZh** [abelsu7/hexo-theme-indigo-plus#2]
不好意思，我又来了。看了控制台信息，TOC的确实生成了锚点链接，但是点击之后不跳转。然后发现只要是有中文，锚点就会失效。求解答~

**Comment by abelsu7** [comment]
@YvanZh 标题中的空格、其他符号在渲染时会被自动替换为`-`。所以标题可以采用以下的形式：

```markdown
## 1. Title
or
## 1-Title
```

而不要使用空格：

```markdown
## 1 Title
会被渲染为 1-Title
```

**Comment by YvanZh** [comment]
我去掉了`.`和空格还是跳转不了。把中文去掉之后，只有数字和英文还有空格和`.`，就可以跳转。

**Comment by abelsu7** [comment]
停掉`hexo server`。重新`hexo clean`、`hexo g`之后再启动`hexo s`试试

**Comment by YvanZh** [comment]
重复试了好几次，确实是中文的锅。我特意写了一下一个英文，一个中文的标题。您帮忙看一眼：
https://yvanzh.top/2019/04/08/Paper-Notes-5/

**Comment by abelsu7** [comment]
@YvanZh 你的其他文章名称是以`_`做分隔符的，TOC 直接渲染成了空格，所以不能跳转，尽量文章名都用`-`分隔，且全部小写。这篇文章我用了一样的标题在本地跑中文是可以跳转的，不知道是什么原因了

**Comment by YvanZh** [comment]
@abelsu7 重新pull了一下，搞定了。应该是我倒腾的时候哪里搞出了毛病。惭愧惭愧，麻烦您了。

**Comment by Monster0303** [comment]
> @ abelsu7重新拉了一下，搞定了。应该是我倒腾的时候哪里搞出了毛病惭愧惭愧，麻烦您了。

不好意思，我也遇到相同的问题，在同一个文章中，英文和数字都正常，只要是有中文，锚点就会失效。

没有序号，纯中文：
```
## 静态算法
[算法](#静态算法)
```
请问怎么解决的？

**Comment by YvanZh** [comment]
@Monster0303 你好，时间太久，我已经记不太清楚是什么原因导致的锚点失效了。你可以先试着重新pull一下主题。
