### ISSUE TITLE
能否支持indigo的自定义页面

### ISSUE THREAD

**Issue by atomrq** [abelsu7/hexo-theme-indigo-plus#4]
您好，试用了indigo-plus觉得很棒，谢谢。
另外，我看到原作者对markdown进行了扩展，主题 Card 分支为自定义页面提供了定制化模块支持。我不太懂这方面的东西，搞不定。作者闲暇能否支持下。

**Comment by abelsu7** [comment]
这部分没有改动，参见 [用户自定义页面功能演示 | hexo-theme-indigo](https://imys.net/custom/)

**Comment by atomrq** [comment]
OK 谢谢！
